on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.13'

    - name: Print git status
      run: git status

    - name: Print Python version
      run: python --version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install tox==4.26.0

    - name: Run
      run: tox

    - name: Check Modified Files
      run: |
        git status --porcelain | findstr .
        if ($LASTEXITCODE -eq 0) {
          echo "There are modified files.`n"
          git status
          exit 1
        }

        echo "Clean working tree."
        exit 0

    - name: Create installer
      run: python create_installer.py